name: Run Postman Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/collection.json \
            --env-var ENDPOINT=${{ secrets.ENDPOINT }} \
            --env-var TOKEN=${{ secrets.TOKEN }} \
            -r cli,junit \
            --reporter-junit-export test-results.xml
